Feat/create expense with split and settlements
GenieWizards/finance-management-api pull request #135
Opened 2024-12-31 16:34 UTC by sub1120

2024-12-31 16:39 UTC, sub1120 commented
@shivamvijaywargi have a look on this error.

<img width="1175" alt="Screenshot 2024-12-31 at 10 00 08 PM" src="https://github.com/user-attachments/assets/7caf207c-ec43-4fa6-b5c3-e478adc46201" />

This error is comming while updating values into settlement table.

File: expense.repository.ts 
Error Line: 57

```js
    await tx
      .insert(settlementModel)
      .values(insertSettlements)
      .onConflictDoUpdate({
        target: settlementModel.id,
        set: conflictUpdateSet(settlementModel, ["senderId", "receiverId", "amount"]),
      });
```

To reproduce the same just comment the last describe block in `expense.test.ts` and run `bun test src/modules/expenses/expense.test.ts `.

2025-01-03 17:27 UTC, sub1120 commented
> @shivamvijaywargi have a look on this error.
> 
> <img alt="Screenshot 2024-12-31 at 10 00 08 PM" width="1175" src="https://private-user-images.githubusercontent.com/43786036/399500883-7caf207c-ec43-4fa6-b5c3-e478adc46201.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5MjU1MDYsIm5iZiI6MTczNTkyNTIwNiwicGF0aCI6Ii80Mzc4NjAzNi8zOTk1MDA4ODMtN2NhZjIwN2MtZWM0My00ZmE2LWI1YzMtZTQ3OGFkYzQ2MjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAzVDE3MjY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyYmE2ODg4NTkzZDUxOWIxZjA1ZDM4OWY1YTg1NzJkNmU4OTZlNjQwZmQ4ZDZiZTkzMmNhYzViYzZhMGY5MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TdjJmBGKDgrRWjpZcTtLQjOV2SqFVq5lLqseq6YDu8M">
> This error is comming while updating values into settlement table. If you notice from ss, drzzel is looking for `senderid` field, but we have passed `senderId`, there is case differnce comming.
> 
> File: expense.repository.ts Error Line: 57
> 
> ```js
>     await tx
>       .insert(settlementModel)
>       .values(insertSettlements)
>       .onConflictDoUpdate({
>         target: settlementModel.id,
>         set: conflictUpdateSet(settlementModel, ["senderId", "receiverId", "amount"]),
>       });
> ```
> 
> To reproduce the same just comment the last describe block in `expense.test.ts` and run `bun test src/modules/expenses/expense.test.ts `.
> 
> Note: Code still need to be refactored so please ingore code quality for time being, let me know if anywhere you want clarifications.

@shivamvijaywargi fyi. I got the solution. I will push the final code soon.

2025-01-04 08:38 UTC, sub1120 commented on src/modules/expenses/expense.validations.ts
> +      amount: z.number(),
Good suggestion! Done.

2025-01-05 10:29 UTC, sub1120 commented on src/modules/splits/split.repository.ts
> +  const [expense] = await db
Its expected. No issue here.

2025-01-05 10:29 UTC, sub1120 commented on src/modules/expenses/expense.test.ts
> +  // describe("POST /expenses as user with splits", () => {
Removed.

2025-01-05 10:31 UTC, sub1120 reviewed
Self review - all good.

2025-01-24 06:29 UTC, shivamvijaywargi requested changes
Appreciate the work you have put in, just a few questions I have, please check and let me know.

2025-01-24 06:29 UTC, shivamvijaywargi commented on src/common/utils/test.util.ts
> +import crypto from "node:crypto";
We are not in the node world, please check the alternative in bun world.

2025-01-24 06:29 UTC, shivamvijaywargi commented on src/modules/expenses/expense.handlers.ts
> +      result.code as 500,
Why typecast it as 500?

2025-01-24 06:29 UTC, shivamvijaywargi commented on src/modules/expenses/expense.routes.ts
> +    body: jsonContentRequired(createExpenseBodySchema, "Expense creation details"),
We have to omit few things like createdAt, updatedAt, id, etc..,

2025-01-25 16:52 UTC, sub1120 commented
> Appreciate the work you have put in, just a few questions I have, please check and let me know.

Thanks for review @shivamvijaywargi i will look into it. I also need some help related to typescript in this PR, I will connect with you regarding same.

2025-02-03 15:40 UTC, shivamvijaywargi commented on src/modules/expenses/expense.validations.ts
> +    },
Pagal hai kya, unnecessary semicolon kaha hai?

2025-02-03 17:36 UTC, sub1120 commented on src/modules/expenses/expense.routes.ts
> +    body: jsonContentRequired(createExpenseBodySchema, "Expense creation details"),
Its omited in `createExpenseBodySchema`, check in `expense.validation.ts`.

2025-02-03 18:01 UTC, shivamvijaywargi approved these changes
LGTM

2025-02-03 18:02 UTC, merged